# Generated by Django 6.0.6 on 2026-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cumulative_risk_score',
            field=models.FloatField(default=0.0, help_text='Running average risk score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, help_text='Stored as lowercase plain text for demo. Use hashed answers in production.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('pet', 'What was the name of your first pet?'), ('school', 'What primary school did you attend?'), ('city', 'In what city were you born?'), ('mother', "What is your mother's maiden name?"), ('car', 'What was the make of your first car?')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_suspicious_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='mfa_level_used',
            field=models.CharField(default='low', help_text='MFA level: low/medium/high', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'login_time'], name='login_histo_user_id_6d3173_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['is_suspicious'], name='login_histo_is_susp_fe4dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='otp_verific_user_id_7a81bb_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='otp_verific_expires_b46ee7_idx'),
        ),
    ]
