# Generated by Django 4.2.7 on 2026-06-08 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('suspicious_login_detected', 'Suspicious Login Detected'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Verification Failed'), ('file_uploaded', 'File Uploaded'), ('file_encrypted', 'File Encrypted'), ('file_decrypted', 'File Decrypted'), ('file_downloaded', 'File Downloaded'), ('file_deleted', 'File Deleted'), ('password_reset', 'Password Reset'), ('profile_updated', 'Profile Updated'), ('user_approved', 'User Approved'), ('user_suspended', 'User Suspended'), ('decryption_error', 'Decryption Error'), ('integrity_failed', 'File Integrity Failed')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force Attempt'), ('unusual_location', 'Unusual Location'), ('multiple_failures', 'Multiple Auth Failures'), ('integrity_violation', 'File Integrity Violation'), ('suspicious_pattern', 'Suspicious Login Pattern')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
