# Generated by Django 6.0.6 on 2026-06-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('suspicious_login_detected', 'Suspicious Login Detected'), ('suspicious_access', 'Suspicious Access Attempt'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Verification Failed'), ('file_uploaded', 'File Uploaded'), ('file_encrypted', 'File Encrypted'), ('file_decrypted', 'File Decrypted'), ('file_downloaded', 'File Downloaded'), ('file_deleted', 'File Deleted'), ('file_integrity_check', 'File Integrity Check'), ('password_reset', 'Password Reset'), ('profile_updated', 'Profile Updated'), ('user_approved', 'User Approved'), ('user_suspended', 'User Suspended'), ('decryption_error', 'Decryption Error'), ('integrity_failed', 'File Integrity Failed')], max_length=50),
        ),
    ]
