# Generated by Django 4.2.7 on 2026-06-08 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='encrypted/')),
                ('original_size', models.BigIntegerField(default=0)),
                ('encryption_type', models.CharField(blank=True, choices=[('AES-128', 'AES-128 (Small files < 1MB)'), ('AES-192', 'AES-192 (Medium files 1-10MB)'), ('AES-256', 'AES-256 (Large files > 10MB)')], max_length=10)),
                ('encryption_key', models.TextField(blank=True)),
                ('encryption_iv', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('encrypted', 'Encrypted'), ('decrypted', 'Decrypted'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for integrity check', max_length=64)),
                ('encryption_time', models.FloatField(default=0.0, help_text='Time in milliseconds')),
                ('decryption_time', models.FloatField(default=0.0, help_text='Time in milliseconds')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encrypted_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
