# Generated by Django 4.2.7 on 2026-06-08 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('login_hour', models.IntegerField()),
                ('device_type', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=100)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action_taken', models.CharField(default='none', max_length=100)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'threat_predictions',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
