# Generated by Django 6.0.6 on 2026-06-10 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='access_count',
            field=models.IntegerField(default=0, help_text='Number of times decrypted/downloaded'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='risk_score_at_upload',
            field=models.FloatField(default=0.0, help_text='User risk score at time of upload'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='sensitivity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='encryption_key',
            field=models.TextField(blank=True, help_text='AES key wrapped with master key (AES-GCM). Production: use AWS KMS.'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='encryption_type',
            field=models.CharField(blank=True, choices=[('AES-128', 'AES-128 (Small files < 1MB)'), ('AES-192', 'AES-192 (Medium files 1–10MB)'), ('AES-256', 'AES-256 (Large files > 10MB or high-risk)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of original plaintext for integrity check', max_length=64),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['user', 'is_deleted'], name='encrypted_f_user_id_7d50b1_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['status'], name='encrypted_f_status_4f204b_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfile',
            index=models.Index(fields=['encryption_type'], name='encrypted_f_encrypt_392a20_idx'),
        ),
    ]
